name: Build Flatpak
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:latest
      options: --privileged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: nz.mega.MEGAsync.yml
          bundle: megasync.flatpak
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: true

      - name: Extract flatpak from zip
        run: |
          unzip megasync-x86_64.flatpak.zip
          ls -lh

      - name: Upload Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          files: megasync.flatpak
          tag_name: latest
          name: "Latest Build"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
